version: '3'
networks:
  devNetwork:
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - devNetwork

  mysql:
    image: mysql:5.7.16
    container_name: mysql
    # restart: unless-stopped
    networks:
      - devNetwork
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql

  redis:
    image: redis:6.0.20-alpine3.18
    container_name: redis
    ports:
      - "6379:6379"
    tty: true
    networks:
      - devNetwork
    volumes:
      - ./redis:/data

  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - php
      - redis
    volumes:
      - ./src:/var/www/
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - devNetwork
  

  